name: 'ecommerce_growth'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_growth'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dev_start_date: '2014-12-19'

models:
  ecommerce_growth:             
    staging:
      +schema: "{{ none if target.name == 'ci' else 'staging' }}"
      +materialized: view
    intermediate:
      +schema: "{{ none if target.name == 'ci' else 'intermediate' }}"
      +materialized: view
    marts:
    # dev: view  -> fast local iteration, no build cost
    # ci/prod: table -> CI mirrors prod
      +materialized: "{{ 'view' if target.name == 'dev' else 'table' }}"
      +schema: "{{ none if target.name == 'ci' else 'intermediate' }}"

data_tests:
  +severity: "{{ 'warn' if target.name == 'dev' else 'error' }}"
  +store_failures: "{{ target.name != 'dev' }}"
