WITH SOURCE AS (
    SELECT * FROM {{ source('internal_data', 'orders') }}
),

RENAMED_AND_CAST AS (
    SELECT
        CAST(ORDER_ID AS STRING) AS ORDER_ID,
        CAST(CREATED_AT AS TIMESTAMP) AS ORDERED_AT,
        CAST(CREATED_AT AS DATE) AS ORDERED_DATE, -- New column for easy daily reporting
        CAST(WEBSITE_SESSION_ID AS STRING) AS SESSION_ID,
        CAST(USER_ID AS STRING) AS USER_ID,
        CAST(PRIMARY_PRODUCT_ID AS STRING) AS PRIMARY_PRODUCT_ID,
        CAST(ITEMS_PURCHASED AS INT) AS ITEMS_PURCHASED,
        CAST(PRICE_USD AS DECIMAL(10, 2)) AS PRICE_USD,
        CAST(COGS_USD AS DECIMAL(10, 2)) AS COGS_USD
    FROM SOURCE
)

SELECT
    *,
    -- Metadata column
    {{ dbt.current_timestamp() }} AS _LOADED_AT
FROM RENAMED_AND_CAST
