WITH SOURCE AS (
    SELECT * FROM {{ source('internal_data', 'website_sessions') }}
),

RENAMED_AND_CAST AS (
    SELECT
        CAST(WEBSITE_SESSION_ID AS STRING) AS SESSION_ID,
        CAST(CREATED_AT AS TIMESTAMP) AS SESSION_AT,
        CAST(CREATED_AT AS DATE) AS SESSION_DATE, -- New column for easy daily reporting
        CAST(USER_ID AS STRING) AS USER_ID,
        CAST(UTM_SOURCE AS STRING) AS UTM_SOURCE,
        CAST(UTM_CAMPAIGN AS STRING) AS UTM_CAMPAIGN,
        CAST(UTM_CONTENT AS STRING) AS UTM_CONTENT,
        CAST(DEVICE_TYPE AS STRING) AS DEVICE_TYPE,
        CAST(HTTP_REFERER AS STRING) AS HTTP_REFERER
    FROM SOURCE
)

SELECT
    *,
    -- Metadata column
    {{ dbt.current_timestamp() }} AS _LOADED_AT
FROM RENAMED_AND_CAST
